from .base import BaseFixer

class LabelFixer(BaseFixer):
    """
    Fixer to ensure all inputs have an associated label.
    """
    def apply(self):
        # Find all input and textarea elements
        for tag_name in ['input', 'textarea']:
            for tag in self.soup.find_all(tag_name):
                # Skip hidden inputs and submit/button types
                if tag.name == 'input' and tag.get('type') in ['hidden', 'submit', 'button', 'image', 'reset']:
                    continue
                
                # Check if it has an id
                tag_id = tag.get('id')
                if not tag_id:
                    # If no ID, we can't easily link a label. 
                    # For MVP, we might generate an ID or just warn.
                    # Let's generate an ID if missing for now to enable the fix.
                    # Actually, let's just warn for now if no ID, to be safe.
                    # But the prompt says "insert a <label> with an autogenerated or inferred label".
                    # So let's generate an ID.
                    import uuid
                    tag_id = f"input_{uuid.uuid4().hex[:8]}"
                    tag['id'] = tag_id
                    self.add_change(f"Generated ID '{tag_id}' for <{tag.name}>")

                # Check if there is a label for this id
                labels = self.soup.find_all('label', attrs={'for': tag_id})
                if not labels:
                    # No label found. Create one.
                    label_text = f"Label for {tag_id}"
                    new_label = self.soup.new_tag("label", attrs={"for": tag_id})
                    new_label.string = label_text
                    
                    # Insert before the input
                    tag.insert_before(new_label)
                    
                    # Add comment
                    self.add_comment(new_label, "added-label")
                    
                    self.add_change(f"Added label to <{tag.name} id=\"{tag_id}\">")
